# Generated by Django 4.2 on 2023-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_user',
            field=models.CharField(default='user', max_length=16),
        ),
    ]
