# Generated by Django 4.2 on 2023-05-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_comment_created_at'),
        ('authors', '0006_alter_author_user'),
    ]

    operations = [
    ]
