# Generated by Django 4.2 on 2023-04-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_author', models.SmallIntegerField(default=0, verbose_name='Рэйтинг')),
                ('author_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(help_text='Name of category - 64 characters', max_length=64, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, verbose_name='Type of post')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('header_post', models.CharField(max_length=128, verbose_name='Title')),
                ('text_post', models.TextField(verbose_name='Text')),
                ('rating_post', models.SmallIntegerField(default=0, verbose_name='Rating')),
                ('is_created', models.BooleanField(default=True, verbose_name='Created')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throughCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.category', verbose_name='Category')),
                ('throughPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.post', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Connection Publication - Category',
                'verbose_name_plural': 'Connections Publications - Categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='authors.PostCategory', to='authors.category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(verbose_name='Comment')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('rating_comment', models.SmallIntegerField(default=0, verbose_name='Rating')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.post', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CategorySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throughCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.category', verbose_name='Category')),
                ('throughSubscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Connection Category-Subscriber',
                'verbose_name_plural': 'Connections Categories-Subscribers',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='authors.CategorySubscriber', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
    ]
